Add static geolocation
software-mansion/react-native-ide pull request #317
Opened 2024-05-28 10:07 UTC by filip131311

This PR adds an ability to set static device location. 

https://github.com/software-mansion/react-native-ide/assets/159789821/fdb8f3f8-58c8-4d80-be04-6e2d89fd91b9

2024-05-28 12:57 UTC, jakub-gonet requested changes

2024-05-28 12:57 UTC, jakub-gonet commented on packages/vscode-extension/src/webview/views/DeviceLocationView.tsx
> +  const [longitude, setLongitude] = useState("");
To be honest, I'd remove all useStates here. The main source of data is coming from `deviceSettings` and you can compute all of transformed data using it. useState + useEffect is an antipattern in React.

2024-05-29 10:13 UTC, filip131311 commented on packages/vscode-extension/src/project/project.ts
> +      longitude: 0,
I added the ability to disable location, but decided to stick to location being set be default, as a little easter egg our office is set as first location.

2024-05-29 10:14 UTC, filip131311 commented on packages/vscode-extension/src/webview/views/DeviceLocationView.tsx
> +  const [longitude, setLongitude] = useState("");
Thank you done!

2024-05-29 13:29 UTC, kacperkapusciak requested changes

2024-05-29 13:29 UTC, kacperkapusciak commented on packages/vscode-extension/src/webview/views/DeviceLocationView.tsx
> +      </select>
this should be a switch https://www.radix-ui.com/primitives/docs/components/switch

2024-05-29 13:29 UTC, kacperkapusciak commented on packages/vscode-extension/src/webview/views/DeviceLocationView.tsx
> +    const lonDirection = event.target[3].value;
```suggestion
const [latitude, latDirection, longitude, lonDirection] = event.target.map(item => item.value);
```

the `.target[0]`, `.target[1]`, `.target[2]`... screams array destructuring.

here it's not a trivial example but I believe it is a bit readable? we could split it to 2 lines as well something like that
```js
  const locationValues = event.target.map(item => item.value);
  const [latitude, latDirection, longitude, lonDirection] = locationValues;
```

2024-05-29 13:29 UTC, kacperkapusciak commented on packages/vscode-extension/src/webview/views/DeviceLocationView.tsx
> +    }
```suggestion
    const isDisabled = e.target.value === "true";
```
why

2024-05-29 13:29 UTC, kacperkapusciak commented on packages/vscode-extension/src/webview/views/DeviceLocationView.tsx
> +  const handleDisableLocation = (e: any) => {
let's not use `any`

2024-05-29 13:29 UTC, kacperkapusciak commented on packages/vscode-extension/src/webview/views/DeviceLocationView.tsx
> +              defaultValue={deviceSettings.location.latitude < 0 ? "S" : "N"}>
i'm not a fan of magic strings like "S" or "N". They either should be constants on top of the file or grouped as an enum as they never change

2024-06-03 20:16 UTC, kmagiera requested changes
We discussed this over call but posting high level comments such that they don't get lost:
 1) let's accept single line input for coords and allow different formatting (use some js libfor parsing). It is convinient to be able to paste the coords from somewhere instead of interacting with four separate controls
 2) don't put form controls below "save" button, the enable/disable switch should be first actually
 3) we don't need save, let's just save on change assuming the provided coords are valid

2024-06-10 09:14 UTC, kmagiera approved these changes
Leaving some minor comments in code to fix before merging

2024-06-10 09:14 UTC, kmagiera commented on packages/vscode-extension/src/common/utils.ts
> +export function throttleWithTrailing<T extends (...args: any[]) => any>(
how is this different than "throttle"? Maybe add some comment here? Also from reading the code it appears like you can actually use the existing method, no?

2024-06-10 12:27 UTC, merged